services:
    server:
        container_name: server
        build:
            context: .
            dockerfile: ./.docker/dev/Dockerfile
        volumes:
            - .:/app
        network_mode: host
        stdin_open: true
        tty: true
